### ISSUE TITLE
Problem with created property

### ISSUE THREAD

**Issue by james-ai** [ericcf/icalendar2#3]
When I try to add the created property I get a NoMethodError.

For example:

``` ruby
calendar.event do
  created "20130130T150116Z"
end
```

I get the following:

``` ruby
NoMethodError: undefined method `new' for nil:NilClass
    from /Users/jamessmith/.rvm/gems/ruby-1.9.3-p0/gems/icalendar2-0.1.1/lib/icalendar2/component/base.rb:66:in `block in define_accessor'
    from (irb):33:in `block in irb_binding'
    from /Users/jamessmith/.rvm/gems/ruby-1.9.3-p0/gems/icalendar2-0.1.1/lib/icalendar2/calendar.rb:53:in `instance_eval'
    from /Users/jamessmith/.rvm/gems/ruby-1.9.3-p0/gems/icalendar2-0.1.1/lib/icalendar2/calendar.rb:53:in `event'
    from (irb):32
    from /Users/jamessmith/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.2/lib/rails/commands/console.rb:47:in `start'
    from /Users/jamessmith/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.2/lib/rails/commands/console.rb:8:in `start'
    from /Users/jamessmith/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.2/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

I'm on Mac 10.8.6 and I think most of the other info is in the exception output above.

**Comment by james-ai** [comment]
Wrote code for this problem.
